services:
  - name: warehouse.clip.atrix
    group: clip.atrix
    url: "http://warehouse.clip.atrix/healthcheck"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
  - name: lightgateway.clip.atrix
    group: clip.atrix
    url: "http://lightgateway.clip.atrix"
    interval: 1m
    conditions:
      - "[STATUS] == 401"
      - "[RESPONSE_TIME] < 1000"
  - name: email.clip.atrix
    group: clip.atrix
    url: "http://email.clip.atrix:4080/healthcheck"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 3000"
  - name: cam1.clip.atrix
    group: clip.atrix
    url: "http://cam1.clip.atrix:9083/healthcheck"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
  - name: cam2.clip.atrix
    group: clip.atrix
    url: "http://cam2.clip.atrix:3080/healthcheck"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
  - name: clipsim.clip.atrix
    group: clip.atrix
    url: "http://clipsim.clip.atrix/healthcheck"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
  - name: siem.clip.atrix
    group: clip.atrix
    url: "http://siem.clip.atrix"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
  - name: ids.clip.atrix
    group: clip.atrix
    url: "http://ids.clip.atrix:2080/healthcheck"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
  - name: architect.clip.atrix
    group: clip.atrix
    url: "http://ids.clip.atrix"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
  - name: iis01.clip.atrix
    group: clip.atrix
    url: "http://iis01.clip.atrix/default.aspx"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
  - name: apply.clip.atrix
    group: clip.atrix
    url: "http://apply.clip.atrix:5080/healthcheck"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
  # .iot
  - name: dyslexa.iot
    group: .iot
    url: "https://dyslexa.iot"
    interval: 1m
    insecure: true
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
  - name: mirandascam.neighborhood.iot
    group: .iot
    url: "http://mirandascam.neighborhood.iot:7080/healthcheck"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
  - name: DNS query
    url: "10.7.3.6" # Address of the DNS server to use
    interval: 30s
    dns:
      query-name: "warehouse.clip.atrix"
      query-type: "A"
    conditions:
      - "[BODY] == 10.7.3.14"
      - "[DNS_RCODE] == NOERROR"
